#!/usr/bin/bash

# Allow mopidy user to access X server
xhost +SI:localuser:mopidy || true

export MOZ_USE_XINPUT2=1

# Setting sound
amixer cset numid=3 1                     || true
amixer sset -D pulse Master 98% unmute    || true
amixer sset Master 98% unmute             || true
amixer -c 1 cset numid=1 98%              || true

(rm -rf ~/.config/*nativefier*/Cache/ || true) &
(cp .config/signalk-nativefier-*/Cookies .config/sk-autopilot-nativefier-*/ || true) &
(rm -rf ~/.opencpn/startcheck.dat ~/.opencpn/_OpenCPN_SILock || true) &

(xset s off || true) &
(xset -dpms || true) &
(xset s noblank || true) &

(evdev-rce || true) &
(twofing --click=first --grab-by-disabling /dev/twofingtouch || true) &

/usr/local/bin/bbn-launcherd &
(sleep 4 && /opt/bbn-launcher/bbn-launcher) &

(sleep 7 && nm-applet) &
(sleep 8 && onboard) &
(sleep 30 && autoadb scrcpy -s '{}') &
(sleep 60 && sh -c 'while ! ping -c 1 -n -w 1 spotify.com; do sleep 20; done;' && \
  systemctl --user reenable raspotify && systemctl --user start raspotify) &
