---
version: 2.1
orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.4
  gcp-cli: circleci/gcp-cli@3.1.0
  gcp-storage: freighthub/gcp-storage@0.2.0
executors:
  boot-linux:
    machine:
      resource_class: large
      image: ubuntu-2004:2022.07.1
  boot-linux-arm:
    machine:
      resource_class: arm.large
      image: ubuntu-2004:2022.07.1
commands:
  git-checkout:
    steps:
      - checkout
      - run: mv install-scripts cross-build-release/
  build-n-publish-debian:
    steps:
      - run: sudo apt-get -y install wget
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-ci.sh
          no_output_timeout: 20m
      - gcp-cli/setup
      - run:
          command: |
            .circleci/publish-gs.sh img bbn-projects/bbn-repo ${PKG_DISTRO}/${PKG_RELEASE}
          no_output_timeout: 40m
  build-debian:
    steps:
      - run: sudo apt-get -y install wget
      - run: chmod a+x .circleci/*.sh
      - run:
          command: |
            .circleci/build-ci.sh
          no_output_timeout: 20m
  do-all:
    steps:
      - git-checkout
      - build-n-publish-debian
  do-build:
    steps:
      - git-checkout
      - build-debian
jobs:
  build-raspbian-bullseye-arm64:
    executor: boot-linux-arm
    environment:
      - DOCKER_IMAGE=arm64v8/debian:bullseye
      - CONTAINER_DISTRO=debian:bullseye
      - PKG_RELEASE=raspbian
      - PKG_DISTRO=bullseye
      - PKG_ARCH=arm64
      - EMU=off
    steps:
      - do-all
  build-only-raspbian-bullseye-arm64:
    executor: boot-linux-arm
    environment:
      - DOCKER_IMAGE=arm64v8/debian:bullseye
      - CONTAINER_DISTRO=debian:bullseye
      - PKG_RELEASE=raspbian
      - PKG_DISTRO=bullseye
      - PKG_ARCH=arm64
      - EMU=off
    steps:
      - do-build
workflows:
  version: 2
  build_all:
    jobs:
      - build-raspbian-bullseye-arm64
